# General configuration for the detection.launch file

detection:
  ir_camera_name: "/camera/ir"
  rgb_camera_name: "/camera/rgb"
  filtered_camera_name: "/filtered_camera"
  
  raw_image_topic: "/image_raw"
  filtered_image_topic: "/image"
  
  ir_camera_info: "/camera/ir/camera_info"
  rgb_camera_info: "/camera/rgb/camera_info"
  
  arduino_topic: "/brightness"
  
serial_node:
  port: "/dev/ttyACM0"
  baud: 115200